import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import { defineConfig, loadEnv, lazyPlugins } from 'vite-plus';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return {
    staged: {
      '*': 'vp check --fix',
    },
    lint: {
      plugins: ['typescript', 'react', 'import'],
      categories: {
        correctness: 'off',
      },
      env: {
        builtin: true,
        browser: true,
        es2020: true,
      },
      ignorePatterns: ['dist', 'node_modules'],
      jsPlugins: [
        {
          name: 'vite-plus',
          specifier: 'vite-plus/oxlint-plugin',
        },
      ],
      overrides: [
        {
          files: ['**/*.{ts,tsx}'],
          rules: {
            'for-direction': 'error',
            'no-async-promise-executor': 'error',
            'no-case-declarations': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-delete-var': 'error',
            'no-dupe-else-if': 'error',
            'no-duplicate-case': 'error',
            'no-empty': 'error',
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-empty-static-block': 'error',
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-fallthrough': 'error',
            'no-global-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-prototype-builtins': 'error',
            'no-regex-spaces': 'error',
            'no-self-assign': 'error',
            'no-shadow-restricted-names': 'error',
            'no-sparse-arrays': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': [
              'error',
              {
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                caughtErrorsIgnorePattern: '^_',
              },
            ],
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-escape': 'error',
            'require-yield': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'no-array-constructor': 'error',
            'no-unused-expressions': 'error',
            'constructor-super': 'off',
            'getter-return': 'off',
            'no-class-assign': 'off',
            'no-const-assign': 'off',
            'no-dupe-class-members': 'off',
            'no-dupe-keys': 'off',
            'no-func-assign': 'off',
            'no-import-assign': 'off',
            'no-new-native-nonconstructor': 'off',
            'no-obj-calls': 'off',
            'no-redeclare': 'off',
            'no-setter-return': 'off',
            'no-this-before-super': 'off',
            'no-unexpected-multiline': 'off',
            'no-unreachable': 'off',
            'no-unsafe-negation': 'off',
            'no-with': 'off',
            'typescript/ban-ts-comment': 'error',
            'typescript/no-duplicate-enum-values': 'error',
            'typescript/no-empty-object-type': 'error',
            'typescript/no-explicit-any': 'error',
            'typescript/no-extra-non-null-assertion': 'error',
            'typescript/no-misused-new': 'error',
            'typescript/no-namespace': 'error',
            'typescript/no-non-null-asserted-optional-chain': 'error',
            'typescript/no-require-imports': 'error',
            'typescript/no-this-alias': 'error',
            'typescript/no-unnecessary-type-constraint': 'error',
            'typescript/no-unsafe-declaration-merging': 'error',
            'typescript/no-unsafe-function-type': 'error',
            'typescript/no-wrapper-object-types': 'error',
            'typescript/prefer-as-const': 'error',
            'typescript/prefer-namespace-keyword': 'error',
            'typescript/triple-slash-reference': 'error',
            'import/no-duplicates': 'error',
            'react/rules-of-hooks': 'error',
            'react/exhaustive-deps': 'off',
            'react/only-export-components': [
              'warn',
              {
                allowConstantExport: true,
              },
            ],
          },
        },
      ],
      options: {
        typeAware: true,
        typeCheck: true,
      },
      rules: {
        'vite-plus/prefer-vite-plus-imports': 'error',
      },
    },
    fmt: {
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 100,
      tabWidth: 2,
      arrowParens: 'always',
      sortPackageJson: false,
      ignorePatterns: ['dist', 'node_modules'],
      // Import grouping previously enforced by eslint-plugin-import/order.
      sortImports: {
        groups: [
          ['value-builtin', 'value-external'],
          'value-internal',
          // `style` matches css/scss; eslint-plugin-import treats those as sibling/parent/index.
          ['value-parent', 'value-sibling', 'value-index', 'style'],
          [
            'type-builtin',
            'type-external',
            'type-internal',
            'type-parent',
            'type-sibling',
            'type-index',
            'type-import',
          ],
          'unknown',
        ],
        internalPattern: [
          '@components/',
          '@store/',
          '@utils/',
          '@services/',
          '@hooks/',
          '@constants',
          '@pages/',
          '@assets/',
        ],
        newlinesBetween: true,
        order: 'asc',
        ignoreCase: true,
      },
    },
    plugins: lazyPlugins(() => [react()]),
    base: '/p3Reload',
    resolve: {
      alias: {
        '@components': resolve(__dirname, './src/components'),
        '@constants': resolve(__dirname, './src/constants'),
        '@services': resolve(__dirname, './src/services'),
        '@assets': resolve(__dirname, './src/assets'),
        '@store': resolve(__dirname, './src/store'),
      },
    },
    test: {
      environment: 'jsdom',
      include: ['src/**/*.test.{ts,tsx}'],
      setupFiles: ['./src/test/setup.ts'],
    },
    build: {
      sourcemap: env.VITE_SOURCEMAP === 'true',
      rollupOptions: {
        output: {
          assetFileNames: 'assets/[name]-[hash][extname]',
          chunkFileNames: 'assets/[name]-[hash].js',
          entryFileNames: 'assets/[name]-[hash].js',
        },
      },
    },
  };
});
