import { baseCalendar } from "./baseFunctions.jsx";
import { socialLinks } from "../socialLinks";
import { events } from "../events";

export const june = [
  {
    date: new Date(2009, 5, 1),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 2),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.stayAwakeInClass,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 3),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 4),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 5),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 6),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 7),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 8),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: { ...events.tartarus, special: true },
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 9),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.noControl,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 10),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 11),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 12),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 13),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 14),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 15),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 16),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 17),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 18),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 19),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 20),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 21),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 22),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 23),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 24),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 25),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 26),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 27),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 28),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 29),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
  {
    date: new Date(2009, 5, 30),
    ...baseCalendar,
    singleTimeEvents: [],
    arcanes: [],
    activities: {
      morning: events.special,
      day: events.doNothing,
      evening: events.doNothing,
    },
  },
];
