import { DormActivitiesNames } from '@services/stats/dormActivities/types';

import {
  IoriGarden,
  IoriBook,
  SanadaKitchen,
  SanadaDVD,
  AmadaKitchen,
  AmadaDVD,
  KoromaruDVD,
  KoromaruBrush,
  AragakiKitchen,
  AragakiGarden,
  MitsuruKitchen,
  MitsuruBook,
  YukariKitchen,
  YukariDVD,
  FuukaGarden,
  FuukaBook,
  AigisGarden,
  AigisBook,
} from './models';

export {
  IoriGarden,
  IoriBook,
  SanadaKitchen,
  SanadaDVD,
  AmadaKitchen,
  AmadaDVD,
  KoromaruDVD,
  KoromaruBrush,
  AragakiKitchen,
  AragakiGarden,
  MitsuruKitchen,
  MitsuruBook,
  YukariKitchen,
  YukariDVD,
  FuukaGarden,
  FuukaBook,
  AigisGarden,
  AigisBook,
};

export const DormActivitiesModels = {
  [DormActivitiesNames.IoriGarden]: IoriGarden,
  [DormActivitiesNames.IoriBook]: IoriBook,
  [DormActivitiesNames.SanadaKitchen]: SanadaKitchen,
  [DormActivitiesNames.SanadaDVD]: SanadaDVD,
  [DormActivitiesNames.AmadaKitchen]: AmadaKitchen,
  [DormActivitiesNames.AmadaDVD]: AmadaDVD,
  [DormActivitiesNames.KoromaruDVD]: KoromaruDVD,
  [DormActivitiesNames.KoromaruBrush]: KoromaruBrush,
  [DormActivitiesNames.AragakiKitchen]: AragakiKitchen,
  [DormActivitiesNames.AragakiGarden]: AragakiGarden,
  [DormActivitiesNames.MitsuruKitchen]: MitsuruKitchen,
  [DormActivitiesNames.MitsuruBook]: MitsuruBook,
  [DormActivitiesNames.YukariKitchen]: YukariKitchen,
  [DormActivitiesNames.YukariDVD]: YukariDVD,
  [DormActivitiesNames.FuukaGarden]: FuukaGarden,
  [DormActivitiesNames.FuukaBook]: FuukaBook,
  [DormActivitiesNames.AigisGarden]: AigisGarden,
  [DormActivitiesNames.AigisBook]: AigisBook,
} as const;
