export const socialLinkFullNames = {
  Amada: 'Ken Amada',
  Aragaki: 'Shinjiro Aragaki',
  Iori: 'Junpei Iori',
  Koromaru: 'Koromaru',
  Akihiko: 'Akihiko Sanada',
  Aeon: 'Aigis',
  Chariot: 'Kazushi Miyamoto',
  Emperor: 'Hidetoshi Odagiri',
  Empress: 'Mitsuru Kirijo',
  Fortune: 'Keisuke Hiraga',
  HangedMan: 'Maiko Oohashi',
  Hermit: 'Maya',
  Hierophant: 'Bunkichi and Mitsuko',
  Justice: 'Chihiro Fushimi',
  Lovers: 'Yukari Takeba',
  Magician: 'Kenji Tomochika',
  Moon: 'Nozomi Suemitsu',
  Priestess: 'Fuuka Yamagishi',
  Star: 'Mamoru Hayase',
  Strength: 'Yuko Nishiwaki',
  Temperance: 'André Laurent Jean "Bebe" Geraux',
  Tower: 'Mutatsu',
};
