import {
  CharacterStatsNames,
  type CharacterStatsLevelType,
  type CharacterStatsNamesType,
} from './types';

export const CharacterStatsLevels: Record<CharacterStatsNamesType, CharacterStatsLevelType[]> = {
  [CharacterStatsNames.Academics]: [
    {
      level: 6,
      points: 230,
      name: 'Genius',
      nextLevelPoints: null,
      previousLevelPoints: 155,
      maxLevel: true,
    },
    {
      level: 5,
      points: 155,
      name: 'Intelligent',
      nextLevelPoints: 230,
      previousLevelPoints: 100,
      maxLevel: false,
    },
    {
      level: 4,
      points: 100,
      name: 'Smart',
      nextLevelPoints: 155,
      previousLevelPoints: 55,
      maxLevel: false,
    },
    {
      level: 3,
      points: 55,
      name: 'Above Average',
      nextLevelPoints: 100,
      previousLevelPoints: 20,
      maxLevel: false,
    },
    {
      level: 2,
      points: 20,
      name: 'Average',
      nextLevelPoints: 55,
      previousLevelPoints: 0,
      maxLevel: false,
    },
    {
      level: 1,
      points: 0,
      name: 'Slacker',
      nextLevelPoints: 20,
      previousLevelPoints: null,
      maxLevel: false,
    },
  ],
  [CharacterStatsNames.Courage]: [
    {
      level: 6,
      points: 80,
      name: 'Badass',
      nextLevelPoints: null,
      previousLevelPoints: 60,
      maxLevel: true,
    },
    {
      level: 5,
      points: 60,
      name: 'Fearless',
      nextLevelPoints: 80,
      previousLevelPoints: 45,
      maxLevel: false,
    },
    {
      level: 4,
      points: 45,
      name: 'Tough',
      nextLevelPoints: 60,
      previousLevelPoints: 30,
      maxLevel: false,
    },
    {
      level: 3,
      points: 30,
      name: 'Determined',
      nextLevelPoints: 45,
      previousLevelPoints: 15,
      maxLevel: false,
    },
    {
      level: 2,
      points: 15,
      name: 'Ordinary',
      nextLevelPoints: 30,
      previousLevelPoints: 0,
      maxLevel: false,
    },
    {
      level: 1,
      points: 0,
      name: 'Timid',
      nextLevelPoints: 15,
      previousLevelPoints: null,
      maxLevel: false,
    },
  ],
  [CharacterStatsNames.Charm]: [
    {
      level: 6,
      points: 100,
      name: 'Charismatic',
      nextLevelPoints: null,
      previousLevelPoints: 70,
      maxLevel: true,
    },
    {
      level: 5,
      points: 70,
      name: 'Popular',
      nextLevelPoints: 100,
      previousLevelPoints: 45,
      maxLevel: false,
    },
    {
      level: 4,
      points: 45,
      name: 'Smooth',
      nextLevelPoints: 70,
      previousLevelPoints: 30,
      maxLevel: false,
    },
    {
      level: 3,
      points: 30,
      name: 'Confident',
      nextLevelPoints: 45,
      previousLevelPoints: 15,
      maxLevel: false,
    },
    {
      level: 2,
      points: 15,
      name: 'Unpolished',
      nextLevelPoints: 30,
      previousLevelPoints: 0,
      maxLevel: false,
    },
    {
      level: 1,
      points: 0,
      name: 'Plain',
      nextLevelPoints: 15,
      previousLevelPoints: null,
      maxLevel: false,
    },
  ],
};
